name: otus_food_app
description: The project of the student Dmitrii Ziidik at the Flutter Mobile Developer course from the educational portal otus.ru

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  injectable: ^1.5.3
  injectable_generator: ^1.5.4
  get_it: ^7.2.0
  json_serializable: ^6.5.4
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.11 
  cached_network_image: ^3.2.2
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  html: ^0.15.0
  http: ^0.13.5
  rive: ^0.9.1
  shared_preferences: ^2.0.15
  path: ^1.8.2
  json_annotation: ^4.7.0
  sqflite: ^2.1.0
  dio: ^4.0.6
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  flutter_bloc: ^8.1.1
  image: ^3.2.0   
  tflite: ^1.1.2 
  tflite_flutter: ^0.9.0
  provider: ^6.0.4
  meta: ^1.8.0
  connectivity_plus: ^3.0.2
  pretty_dio_logger: ^1.1.1  
  go_router: ^5.2.4
  otus_plugin_bluetooth: 
    git: 
      url: https://github.com/vachtung-gigabidze/otus_bluetooth_plugin.git
      ref : main   
  cupertino_icons: ^1.0.2
  permission_handler: ^9.2.0
  flutter_isolate: ^2.0.4

  mocktail: ^0.3.0
dev_dependencies:
  build_runner: ^2.2.0

  flutter_test:  
    sdk: flutter
 
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animate/ 
    - assets/tensorflow/labels.txt
    - assets/tensorflow/model_unquant.tflite
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 900
  
