name: otus_food_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"
  # sdk: ">=2.17.0 <3.0.0"

dependencies:
  

  flutter:
    sdk: flutter

  injectable: ^1.5.3
  injectable_generator: ^1.5.4
  get_it: ^7.2.0
  json_serializable: ^6.5.4
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.11 
  cached_network_image: ^3.2.2
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  html: ^0.15.0
  http: ^0.13.5
  rive: ^0.9.1
  shared_preferences: ^2.0.15
  path: ^1.8.2
  json_annotation: ^4.7.0
  sqflite: ^2.1.0


  dio: ^4.0.6
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  flutter_bloc: ^8.1.1

  image: ^3.2.0   
  tflite: ^1.1.2 
  tflite_flutter: ^0.9.0
  provider: ^6.0.4
  meta: ^1.8.0

  connectivity_plus: ^3.0.2
  pretty_dio_logger: ^1.1.1  
  go_router: ^5.2.4


  otus_plugin_bluetooth: 
    git: 
      url: https://github.com/vachtung-gigabidze/otus_bluetooth_plugin.git
      ref : main

    # When depending on this package from a real application you should use:
    #   otus_plugin_bluetooth: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    
  # tflite_flutter_helper: ^0.3.1
  # tflite_flutter: ^0.9.0 
  # tflite_flutter_helper: 
  #   git: 
  #     url: https://github.com/elephantum/tflite_flutter_helper.git
  #     ref: a7d7a59a33f7cffa0a2a12ab05625807622cc97a
  # firebase_core: ^1.24.0
  # cloud_firestore: ^3.5.1

 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  permission_handler: ^9.2.0

dev_dependencies:
  build_runner: ^2.3.2

  flutter_test:  
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animate/
    # - assets/model/recipes.json
    # - assets/model/fridge.json
    # - assets/model/user.json
    - assets/tensorflow/labels.txt
    - assets/tensorflow/model_unquant.tflite
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 900
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
